//===-- MyCPUInstPrinter.h - MyCPU InstPrinter -------------------*- C++ -*-===//

#ifndef LLVM_LIB_TARGET_MYCPU_MCTARGETDESC_MYCPUINSTPRINTER_H
#define LLVM_LIB_TARGET_MYCPU_MCTARGETDESC_MYCPUINSTPRINTER_H

#include "llvm/MC/MCInstPrinter.h"

namespace llvm {

class MyCPUInstPrinter : public MCInstPrinter {
public:
  MyCPUInstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                   const MCRegisterInfo &MRI);

  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;
  std::pair<const char *, uint64_t>
  getMnemonic(const MCInst &MI) const override;

  // Automatically generated by TableGen
  void printInstruction(const MCInst *MI, uint64_t Address, raw_ostream &O);
  const char *getRegisterName(MCRegister Reg);

  // Operand printers
  void printOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printU5Imm(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printU4Imm(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printU3Imm(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printSImm15(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printSImm10(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printBranchTarget(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printCallTarget(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printRegName(raw_ostream &O, MCRegister Reg) override;
};

} // namespace llvm

#endif
